engines:
  fixme:
    enabled: false
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true

ratings:
  paths: 
    - "**.go"

exclude_paths:
- test/
- build/
- vendor/
- CHANGELOG.md
