# https://golangci-lint.run/docs/configuration/file
version: "2"
linters:
  default: standard
formatters:
  enable:
  - gofmt
  - gci
  - goimports
  - golines
#issues:
#  option: value
#output:
#  option: value
#run:
#  option: value
#severity:
#  option: value
