name: CI

on: [push, pull_request]

jobs:

  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.12.7'
      - run: 'go version'
      - name: 'build'
        run: 'make cross-compile'
      - name: 'test'
        run: 'make integration-test'
